model_name_or_path: /path/to/InternVL3_8B_Instruct_hf
trust_remote_code: true
image_max_pixels: 262144

stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all


dataset: qwen2vl_supervised_train_remove_dup
template: intern_vl
cutoff_len: 4096
max_samples: 45000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: /path/to/output_dir
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: auto
video_maxlen: 4

## eval
val_size: 0.04
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500